### ISSUE TITLE
Multiple masks

### ISSUE THREAD

**Issue by alexcroox** [faradayio/Leaflet.CanvasMask#1]
Is it possible to have multiple masks similar to http://domoritz.de/vbb-coverage/

**Comment by summer4096** [comment]
If you want to mask multiple features, you can pass them all within a geojson FeatureCollection. While the example only demonstrates the masking a single feature, you can specify as many as you'd like.

Here's a quick and poorly drawn example of a geojson object that demonstrates this: https://gist.github.com/devTristan/74468ab200f9d0b67e1f

**Comment by alexcroox** [comment]
Nice, if I add layers every x seconds to that collection will it update automatically or do I need to keep re-initialising it every time I change the data?

**Comment by summer4096** [comment]
Use `maskLayer.setData` for that. It takes one argument, which should be a geojson object.

The second example in the readme waits one second, then changes the color and data displayed on the mask. This is done without re-initializing and triggers an immediate redraw.

**Comment by summer4096** [comment]
Re-open if you need more help w/ this.
